version: "3.8"

services:
  postgres:
    image: postgres:11:5
    restart: always
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
